### ISSUE TITLE
How do we run the ATB calc with the 2022 ATB workbook?

### ISSUE THREAD

**Issue by apalomES** [NREL/ATB-calc#14]
Running the following with default config results in _AssertionError: Net Capacity Factor (%): First year should be 2021, got 2020 instead_.
`procWind = LandBasedWindProc(atb_electricity_workbook, crp=crp, case=financial_case); 
procWind.run()`

Updating the config BASE_YEAR = 2020 results in _AssertionError: ITC schedule not found in tax credit data. Looking for "ITC Schedule/*" in:_

Any advice? I'm using the "2022 v3 ATB Mid-year update 2-15-2023.xlsx" workbook.

**Comment by brtietz** [comment]
Each release of ATB-calc is designed to work with a specific edition of the ATB workbook. We don't have an official release for the 2022 workbook, but you could try checking out commit 0b5b625b39e2fd85e5e410151d2856f3804da938 as that was from the same timeframe as that workbook. The example notebooks are in the lcoe_calculator folder as we hadn't finalized the folder structure yet.

**Comment by brtietz** [comment]
Closing due to lack of traffic.
